---
extends: 
  - stylelint-config-standard
  - stylelint-config-recess-order
rules:
  declaration-no-important:
  no-descending-specificity:
  value-keyword-case:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - svg-load
        - mixin
        - define-mixin
  function-name-case:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  property-no-unknown:
    - true
    - ignoreProperties:
        - composes